bpftool: Query only cgroup-related attach types
BugLink: https://bugs.launchpad.net/bugs/2134382

When CONFIG_NETKIT=y,
bpftool-cgroup shows error even if the cgroup's path is correct:

$ bpftool cgroup tree /sys/fs/cgroup
CgroupPath
ID       AttachType      AttachFlags     Name
Error: can't query bpf programs attached to /sys/fs/cgroup: No such device or address

>From strace and kernel tracing, I found netkit returned ENXIO and this command failed.
I think this AttachType(BPF_NETKIT_PRIMARY) is not relevant to cgroup.

bpftool-cgroup should query just only cgroup-related attach types.

v2->v3:
  - removed an unnecessary check

v1->v2:
  - used an array of cgroup attach types

Signed-off-by: Kenta Tada <tadakentaso@gmail.com>
Reviewed-by: Quentin Monnet <qmo@kernel.org>
Link: https://lore.kernel.org/r/20240607111704.6716-1-tadakentaso@gmail.com
Signed-off-by: Alexei Starovoitov <ast@kernel.org>
(cherry picked from commit 98b303c9bf05dae932efbd71e18d81f6c64f20d8)
[diewald: prerequisite for b69d4413aa19 ("bpftool: Fix cgroup command to
only show cgroup bpf programs") that we missed when including the
linux-6.12.y backport with v6.12.35]
Signed-off-by: Manuel Diewald <manuel.diewald@canonical.com>
Acked-by: Edoardo Canepa <edoardo.canepa@canonical.com>
Acked-by: Mehmet Basaran <mehmet.basaran@canonical.com>
Signed-off-by: Mehmet Basaran <mehmet.basaran@canonical.com>